spring.application.name=mcm


#  SERVER
server.port=8090

#  DATABASE (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/mcm_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=prasha0703
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#  JWT CONFIG
jwt.secret=3n6G7vR9yU1jLq2P8kS0dW4xZ8aV6rN1bY3mJ5pQ7hE9tU2lK4cF0gH8sX6wZ1qF2eT9uR8yP3mN4xQ5jK6vH7sL8dZ9aW0bE1cV2
jwt.expirationMs=86400000
# 24 hours in milliseconds

#  LOGGING
logging.level.org.springframework=INFO
logging.level.com.mcm.app=DEBUG

#  DEVTOOLS (AUTO RESTART)
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

#  OTHER SETTINGS
spring.jackson.serialization.write-dates-as-timestamps=false
